export type { ExportFormat, Stage } from './types'
export { startRecording } from './capture'
export type { Recording, RecordingSession } from './capture'
export { webmToGif, autoScale, DEFAULT_MAX_DIMENSION } from './encode'
export type { GifOptions, Crop } from './encode'
export { webmToMp4 } from './encodeMp4'
export type { Mp4Options } from './encodeMp4'
export { compose, composedSize } from './compose'
export type { Scene, Frame, Fit, ScreenRect, FrameLayout, SrcRect } from './compose'
export { FRAMES } from './frames'
